#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     towerLow,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     towerHigh,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     spinner,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    ClawVertical,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    ClawLeft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    ClawRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Gamepad Control
	Alex House

	This program is the tele-op program for the FTC challenge. It uses multi-threading
	in order to process many simultaneous actions at once. Sets of gamepad controls
	are encapsulated in individual tasks, which all run simultaneously and are started
	in the main task, which does nothing.

	This version supports:
		- Driving with the driving gamepad's D-pad
		- Switching between drive speeds with the driving gamepad's triggers.
*/

// Constants:
const byte clawDownPosition = 250;
const byte clawUpPosition = 140;
const byte clawClosedPosition = 130;

#include "JoystickDriver.c"
#include "GamepadAccessors.h"
#include "DriverController.h"
#include "ActionController.h"

task main()
{
	waitForStart();

	servo[ClawVertical] = clawDownPosition;
	servo[ClawLeft] = 0;
	servo[ClawRight] = 255;

	// Tasks related to the Driver controller
	StartTask(DPadDrive);
	StartTask(DrivingSpeedChange);

	// Tasks related to the Action controller
	StartTask(SpinnerSpin);
	StartTask(DPadTowerMove);
	StartTask(SpongeClawMove);

	while(true)
	{
		wait1Msec(1000);	// Our gamepads do all of the work in this mode, and other tasks handle input.
	}
}
