#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorB,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorC,        tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Zachary Abbott, testing program
  motor B is the left one, the front of robot is the NXT brick...
  Motor C is right...



*/


void encodeTurnB(int deg,int speed){
  nMotorEncoder[motorB] = 0;
	nMotorEncoderTarget[motorB] = deg;
	motor[motorB] = speed;

	while(nMotorRunState[motorB] != runStateIdle)
	{
	  // Do not continue.

	}
	motor[motorB] = 0;
}

void encodeTurnC(int deg,int speed){
  nMotorEncoder[motorC] = 0;
	nMotorEncoderTarget[motorC] = deg;
	motor[motorC] = (speed/-1);

	while(nMotorRunState[motorC] != runStateIdle)
	{
	  // nothing to see here
	}
	motor[motorC] = 0;
}

void simpleTurn(string moto, int rota){
  if(moto == "B") {
     encodeTurnB((rota * 360), 75);
  }
  if(moto == "C") {
     encodeTurnC((rota * 360), 75);
  }

}


// the preset

void drivefor(int rota, int speed){ // may change it from deg to rotations (1 rota = 360 deg)

  nSyncedMotors = synchBC;
  int deg = rota * 360;
  nMotorEncoder[motorC] = 0;
  nMotorEncoder[motorB] = 0;
  nMotorEncoderTarget[motorB] = deg;
	nMotorEncoderTarget[motorC] = deg;
	motor[motorB] = speed;
	motor[motorC] = (speed/-1);
	while(nMotorRunState[motorB] != runStateIdle && nMotorRunState[motorC] != runStateIdle){

	}
	motor[motorB]=0;
	motor[motorC]=0;
}

void driveRight(int speed){
  nSyncedMotors = synchBC;
  nMotorEncoder[motorC] = 0;
  nMotorEncoder[motorB] = 0;
  nMotorEncoderTarget[motorB] = 720;
	nMotorEncoderTarget[motorC] = 720;
	motor[motorB] = speed;
	motor[motorC] = speed;
	while(nMotorRunState[motorB] != runStateIdle && nMotorRunState[motorC] != runStateIdle){

	}
	motor[motorB]=0;
	motor[motorC]=0;
}
void driveLeft(int speed){
  nSyncedMotors = synchBC;
  nMotorEncoder[motorC] = 0;
  nMotorEncoder[motorB] = 0;
  nMotorEncoderTarget[motorB] = 720;
	nMotorEncoderTarget[motorC] = 720;
	motor[motorB] = -speed;
	motor[motorC] = -speed;
	while(nMotorRunState[motorB] != runStateIdle && nMotorRunState[motorC] != runStateIdle){

	}
	motor[motorB]=0;
	motor[motorC]=0;
}




task main(){

  motor[motorB] = 0;
  motor[motorC] = 0;
  drivefor(1,75);
  driveRight(75);
  driveLeft(75);
  drivefor(1,-75);
  encodeTurnB(360, 25);
  encodeTurnC(360, 25);
  simpleTurn("B",3);
  simpleTurn("C",3);
}
